// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250309052348_GetPersons_StoredProcedure")]
    partial class GetPersons_StoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            CountryName = "Palestinian Territory"
                        },
                        new
                        {
                            CountryId = new Guid("501c6d33-1bbe-45f1-8fbd-2275913c6218"),
                            CountryName = "China"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PersonCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PersonDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonEmail")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonGender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("PersonReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("PersonCountryId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("c03bbe45-9aeb-4d24-99e0-4743016ffce9"),
                            PersonAddress = "4 Parkside Point",
                            PersonCountryId = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            PersonDOB = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "mwebsdale0@people.com.cn",
                            PersonGender = "Female",
                            PersonName = "Marguerite",
                            PersonReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("c3abddbd-cf50-41d2-b6c4-cc7d5a750928"),
                            PersonAddress = "6 Morningstar Circle",
                            PersonCountryId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            PersonDOB = new DateTime(1990, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "ushears1@globo.com",
                            PersonGender = "Female",
                            PersonName = "Ursa",
                            PersonReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("c6d50a47-f7e6-4482-8be0-4ddfc057fa6e"),
                            PersonAddress = "73 Heath Avenue",
                            PersonCountryId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            PersonDOB = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "fbowsher2@howstuffworks.com",
                            PersonGender = "Male",
                            PersonName = "Franchot",
                            PersonReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("d15c6d9f-70b4-48c5-afd3-e71261f1a9be"),
                            PersonAddress = "83187 Merry Drive",
                            PersonCountryId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            PersonDOB = new DateTime(1987, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "asarvar3@dropbox.com",
                            PersonGender = "Male",
                            PersonName = "Angie",
                            PersonReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("89e5f445-d89f-4e12-94e0-5ad5b235d704"),
                            PersonAddress = "50467 Holy Cross Crossing",
                            PersonCountryId = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            PersonDOB = new DateTime(1995, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "ttregona4@stumbleupon.com",
                            PersonGender = "Gender",
                            PersonName = "Tani",
                            PersonReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("2a6d3738-9def-43ac-9279-0310edc7ceca"),
                            PersonAddress = "97570 Raven Circle",
                            PersonCountryId = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            PersonDOB = new DateTime(1988, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "mlingfoot5@netvibes.com",
                            PersonGender = "Male",
                            PersonName = "Mitchael",
                            PersonReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("29339209-63f5-492f-8459-754943c74abf"),
                            PersonAddress = "57449 Brown Way",
                            PersonCountryId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            PersonDOB = new DateTime(1983, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "mjarrell6@wisc.edu",
                            PersonGender = "Male",
                            PersonName = "Maddy",
                            PersonReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("ac660a73-b0b7-4340-abc1-a914257a6189"),
                            PersonAddress = "4 Stuart Drive",
                            PersonCountryId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            PersonDOB = new DateTime(1998, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "pretchford7@virginia.edu",
                            PersonGender = "Female",
                            PersonName = "Pegeen",
                            PersonReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("012107df-862f-4f16-ba94-e5c16886f005"),
                            PersonAddress = "413 Sachtjen Way",
                            PersonCountryId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            PersonDOB = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "hmosco8@tripod.com",
                            PersonGender = "Male",
                            PersonName = "Hansiain",
                            PersonReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("cb035f22-e7cf-4907-bd07-91cfee5240f3"),
                            PersonAddress = "484 Clarendon Court",
                            PersonCountryId = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            PersonDOB = new DateTime(1997, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "lwoodwing9@wix.com",
                            PersonGender = "Male",
                            PersonName = "Lombard",
                            PersonReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("28d11936-9466-4a4b-b9c5-2f0a8e0cbde9"),
                            PersonAddress = "2 Warrior Avenue",
                            PersonCountryId = new Guid("501c6d33-1bbe-45f1-8fbd-2275913c6218"),
                            PersonDOB = new DateTime(1990, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "mconachya@va.gov",
                            PersonGender = "Female",
                            PersonName = "Minta",
                            PersonReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("a3b9833b-8a4d-43e9-8690-61e08df81a9a"),
                            PersonAddress = "9334 Fremont Street",
                            PersonCountryId = new Guid("501c6d33-1bbe-45f1-8fbd-2275913c6218"),
                            PersonDOB = new DateTime(1987, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonEmail = "vklussb@nationalgeographic.com",
                            PersonGender = "Female",
                            PersonName = "Verene",
                            PersonReceiveNewsLetters = true
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("PersonCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
